
# In case the platform does NOT support this type of sensors

obj-$(CONFIG_LGD_INCELL_TD4100_HD_SF3) += rt4832/
obj-$(CONFIG_LEDS_RT4832_LV5) += rt4832_lv5/
obj-$(CONFIG_LEDS_RT4832_PH1) += rt4832_ph1/
obj-$(CONFIG_LEDS_RT4832) += rt4832/
obj-$(CONFIG_LEDS_LM3632) += lm3632/
obj-$(CONFIG_LEDS_DW8767) += dw8767/
obj-$(CONFIG_LEDS_LM3648) += lm3648/

obj-$(CONFIG_LEDS_RT4832_SF3) += rt4832_sf3/
obj-$(CONFIG_LEDS_RT4832_PH1) += rt4832_ph1/
obj-$(CONFIG_LEDS_RT4832_K6PNA) += rt4832_k6pna/
