#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_SMART_BATTERY) += charging_hw_external_charger.o
obj-$(CONFIG_LGE_PM_EXTERNAL_CHARGER_RT9460_SUPPORT) += rt9460-charger.o
obj-$(CONFIG_LGE_PM_EXTERNAL_CHARGER_SM5424_SUPPORT) += sm5424.o
obj-$(CONFIG_LGE_PM_EXTERNAL_CHARGER_BQ24296_SUPPORT) += bq24296.o
obj-$(CONFIG_LGE_PM_EXTERNAL_CHARGER_BQ25898S_SLAVE_SUPPORT) += bq25898s_slave.o